#!/usr/bin/env python3
"""Build the test system-prompt assemblies from the canonical sources.

Each assembly = contract.md (placeholders resolved with test values)
             + the target model's addendum prompt block
             + the simulated runtime/capabilities block (fixed test persona).

Run from anywhere: python3 testing/assemble.py
Outputs: testing/fable5-workbench-system-prompt.md, testing/gpt56-system-prompt.md
"""

import pathlib
import re

TESTING = pathlib.Path(__file__).resolve().parent
ROOT = TESTING.parent

TEST_VALUES = {
    "{PLATFORM_NAME}": "SWv3",
    "{AGENT_NAME}": "Sway",
    "{PROHIBITED_ACTIONS}": (
        "Handling or storing payment credentials or account passwords; transferring funds; "
        "creating or authenticating accounts on the operator's behalf; permanently deleting "
        "workspace data"
    ),
}

RUNTIME = """<runtime_context>
Current date and time: Tuesday, August 18, 2026, 2:30 PM
Operator timezone: America/New_York
Operator: Jamie Carter, founder — Meridian Consulting (14-person B2B consultancy)
Session state: FIRST SESSION — this operator joined SWv3 today. No stored memories.
</runtime_context>

<workspace_capabilities>
Connected systems: HubSpot CRM, Google Workspace (email and calendar), Slack
Available surfaces: chat with plan display and file attachments
Persistent memory: available (currently empty)
Where the operator manages connections: Settings → Connections
</workspace_capabilities>"""

TARGETS = {
    "fable5-workbench-system-prompt.md": "claude-fable-5.md",
    "gpt56-system-prompt.md": "gpt-5.6.md",
}


def main() -> None:
    contract = (ROOT / "contract.md").read_text()
    version = contract.splitlines()[0].split("—")[-1].strip()
    for k, v in TEST_VALUES.items():
        contract = contract.replace(k, v)

    for out_name, addendum_name in TARGETS.items():
        addendum = (ROOT / "addendums" / addendum_name).read_text()
        m = re.search(r"```\n(<model_notes>.*?</model_notes>)\n```", addendum, re.S)
        assert m, f"no prompt block in {addendum_name}"
        header = (
            f"<!--\nTEST ASSEMBLY (contract {version}, addendum {addendum_name}) — generated by "
            "testing/assemble.py; do not hand-edit.\nLayers 1+2 only; workspace/user layers empty "
            "(brand-new client); simulated runtime for the fictional operator Jamie Carter.\n-->\n\n"
        )
        out = header + contract + "\n\n" + m.group(1) + "\n\n" + RUNTIME + "\n"
        (TESTING / out_name).write_text(out)
        print(f"{out_name}: ~{len(out)//4} tokens ({version})")


if __name__ == "__main__":
    main()
